accueil/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('accueil.views',
    url(r'^$', 'page_accueil'),
)

blog/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('blog.views',
    url(r'^$', 'accueil'),
    url(r'^article/(?P<id>\d+)$', 'lire'),
)

contact/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('contact.views',
    url(r'^$', 'contact'),
)

jardin_buissonnier/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from blog import views
from accueil import views
from jardins import views
from contact import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^', include('accueil.urls')),
    url(r'^jardins/', include('jardins.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jardins/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('jardins.views',
    url(r'^$', 'jardin_accueil'),
)

accueil/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

class Categorie(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom
        
        
class Article(models.Model):
    titre = models.CharField(max_length=100)
    contenu = models.TextField(null=True)
    date = models.DateTimeField(auto_now_add=True, auto_now=False, 
                                verbose_name="Date de parution")
    photo = models.ImageField()
    categorie = models.ForeignKey('Categorie')


    def __str__(self):
        """ 
        Cette méthode que nous définirons dans tous les modèles
        nous permettra de reconnaître facilement les différents objets que 
        nous traiterons plus tard et dans l'administration
        """
        return self.titre

class Jardin(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom
        
               
        
class Legume(models.Model):
    nom = models.CharField(max_length=30)
    photo = models.ImageField()
    jardin = models.ForeignKey('Jardin')
    prix = models.DecimalField(max_digits=6, decimal_places=2,verbose_name="Prix au kilo")
    disponible = models.BooleanField(default=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.nom
        
        

contact/models.py
from django.db import models

# Create your models here.

jardins/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    nom = forms.CharField(max_length=20, label="Nom, Prénom")
    mail = forms.EmailField(label="Adresse email")
    numero = forms.CharField(max_length=10, label="Numéro de téléphone", required=False)
    message = forms.CharField(widget=forms.Textarea)

accueil/views.py
from django.shortcuts import render

# Create your views here.#-*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404


# return redirect("https://www.djangoproject.com")

   
def page_accueil(request):
    return render(request, 'accueil/accueil.html')

blog/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from datetime import datetime
from blog.models import Article, Legume

# return redirect("https://www.djangoproject.com")

    
def accueil(request):
    """ Afficher tous les articles de notre blog """
    articles = Article.objects.all() # Nous sélectionnons tous nos articles
    return render(request, 'blog/blog_accueil.html', {'derniers_articles': articles})

def lire(request, id):
    article = get_object_or_404(Article, id=id)
    return render(request, 'blog/blog_lire.html', {'article':article})

contact/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, redirect, get_object_or_404

from contact.forms import ContactForm

# return redirect("https://www.djangoproject.com")


def contact(request):
    if request.method == 'POST':  # S'il s'agit d'une requête POST
        form = ContactForm(request.POST)  # Nous reprenons les données

        if form.is_valid(): # Nous vérifions que les données envoyées sont valides
            # Ici nous pouvons traiter les données du formulaire

            nom = form.cleaned_data['nom']
            mail = form.cleaned_data['mail']
            numero = form.cleaned_data['numero']
            message = form.cleaned_data['message']

            try:
                send_mail("Message du jardin buissonnier de %s" % nom, message, mail, ['emma.prudent@laposte.net'])
            except BadHeaderError:
                print("marche pas")
                return HttpResponse('Invalid header found.')
            # Nous pourrions ici envoyer l'e-mail grâce aux données que nous venons de récupérer
            envoi = True

    else: # Si ce n'est pas du POST, c'est probablement une requête GET
        form = ContactForm()  # Nous créons un formulaire vide
        
    return render(request, 'contact/contact_accueil.html',locals())

jardins/views.py
from django.shortcuts import render

# Create your views here.#-*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404


# return redirect("https://www.djangoproject.com")

   
def jardin_accueil(request):
    return render(request, 'jardins/jardin_accueil.html')

accueil/templates/accueil/accueil.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Le Jardin Buissonnier {% endblock %}

        {% block content %}
        <div id="sections">
            <div id="encemoment">    
                <div class="bandeau_entete"> <span class="titre"> En ce moment </span> </div>
                <div class="bandeau_pied">  
                    <span class="description"> Les tomates </span>
                    <a href="#" class="bouton">Lire plus &#9656; </a>
                </div>
            </div>     

            <div id="derniersarticles">    
                <div class="bandeau_entete">  <span class="titre"> Derniers articles </span> </div>
                <div class="bandeau_pied"> 
                <span class="description"> Le jardin au mois de juin </span>
                <a href="#" class="bouton">Lire plus &#9656; </a>
                </div>
            </div>   
        </div>
        <div id="quisommesnous">
            <div class="titre_fond">Qui sommes-nous ?</div>
            <img src="{% static 'img/mama.jpg' %}" alt="" style="width:240px; height: auto;display: block;margin-left: auto;margin-right: auto;"/>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur...</p>
            <a href="{% url "contact.views.contact" %}" class="bouton_blanc">Lire plus &#9656; </a>
            <span id="triangle"> <img src="{% static 'img/triangle.svg' %}" alt="" style="width:50px; height: auto;"/></span>
 
    {% endblock%}    

{% block aside %}{% endblock %}

accueil/templates/accueil/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Le Jardin Buissonnier {% endblock %}

        {% block content %}
        <div id="sections">
            <div id="encemoment">    
                <div class="bandeau_entete"> <span class="titre"> En ce moment </span> </div>
                <div class="bandeau_pied">  
                    <span class="description"> Les tomates </span>
                    <a href="#" class="bouton">Lire plus &#9656; </a>
                </div>
            </div>     

            <div id="derniersarticles">    
                <div class="bandeau_entete">  <span class="titre"> Derniers articles </span> </div>
                <div class="bandeau_pied"> 
                <span class="description"> Le jardin au mois de juin </span>
                <a href="#" class="bouton">Lire plus &#9656; </a>
                </div>
            </div>   
        </div>
        <div id="quisommesnous">
            <div class="titre_fond">Qui sommes-nous ?</div>
            <img src="{% static 'img/mama.jpg' %}" alt="" style="width:240px; height: auto;display: block;margin-left: auto;margin-right: auto;"/>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur...</p>
            <a href="#" class="bouton_blanc">Lire plus &#9656; </a>
            <span id="triangle"> <img src="{% static 'img/triangle.svg' %}" alt="" style="width:50px; height: auto;"/></span>
 
    {% endblock%}    

blog/templates/blog/accueil.html
<h1>Bienvenue sur le blog des crêpes bretonnes !</h1>

{% for article in derniers_articles %}
    <div class="article">
    	<h3>{{ article.titre }}</h3>
    	<p>{{ article.contenu|truncatewords_html:80 }}</p>
        <p><a href="{% url "blog.views.lire" article.id %}">Lire la suite</a>
    </div>
{% empty %}
    <p>Aucun article.</p>
{% endfor %}

blog/templates/blog/blog_accueil.html
{% extends "base.html" %}
{% block title %}Le Jardin Buissonnier : Le Blog{% endblock %}
{% block content %}
 <div style="padding-left:150px; padding-right:150px;">    
{% for article in derniers_articles %}
    <p class="titre_article" style="margin:0;">{{ article.titre }}</p>
    	<div class="ligne_verte"> &nbsp; </div>
    <div class="liste_article">
    <div class="image_left"><img src="{{ article.photo.url }}" class="photos_vue_article"/> </div>
    <div class="article_right">      
    	
    	<p>{{ article.contenu|truncatewords_html:40 }}</p>
        <p><a href="{% url "blog.views.lire" article.id %}" class="bouton_vert">Lire plus &#9656; </a></p>
    </div>
    </div>
{% empty %}
    <p>Aucun article.</p>
{% endfor %}
</div>
{% endblock %}

blog/templates/blog/blog_lire.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Le Jardin Buissonnier : Le Blog{% endblock %}
{% block content %}
 <div style="padding-left:150px; padding-right:150px;">
 <div class="div_container">   
    <span class="nav_article"> &#9666; Article précédent </span>
    <span class="nav_article"> Article suivant &#9656;</span>
 </div>

 <div class="div_container_flex_end">
 <p class="titre_article">{{ article.titre }}</p>
 <p class="publication_article">article publié le {{ article.date|date:"DATE_FORMAT" }} à {{ article.date|date:"TIME_FORMAT" }}</p>
</div>

 <div class="ligne_verte"> &nbsp; </div>
 
 <div class="div_container">
<img src="{{ article.photo.url }}" class="photos_article"/>
<div class="contenu_article">{{ article.contenu|linebreaks }}</div>
 </div>
 
  <div class="div_container" style="padding-top:20px;">   
    <span class="nav_article"> &#9666; Article précédent </span>
    <span class="nav_article"> Article suivant &#9656; </span>
 </div>
</div>
{% endblock %}

 

blog/templates/blog/date.html
<h1>Bienvenue sur mon blog</h1>

<p>La date actuelle est : {{ date }}</p>

blog/templates/blog/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Le Jardin Buissonnier {% endblock %}

        {% block content %}
        <div id="sections">
            <div id="encemoment">    
                <div class="bandeau_entete"> <span class="titre"> En ce moment </span> </div>
                <div class="bandeau_pied">  
                    <span class="description"> Les tomates </span>
                    <a href="#" class="bouton">Lire plus &#9656; </a>
                </div>
            </div>     

            <div id="derniersarticles">    
                <div class="bandeau_entete">  <span class="titre"> Derniers articles </span> </div>
                <div class="bandeau_pied"> 
                <span class="description"> Le jardin au mois de juin </span>
                <a href="#" class="bouton">Lire plus &#9656; </a>
                </div>
            </div>   
        </div>
        <div id="quisommesnous">
            <div class="titre_fond">Qui sommes-nous ?</div>
            <img src="{% static 'img/mama.jpg' %}" alt="" style="width:240px; height: auto;display: block;margin-left: auto;margin-right: auto;"/>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur...</p>
            <a href="#" class="bouton_blanc">Lire plus &#9656; </a>
            <span id="triangle"> <img src="{% static 'img/triangle.svg' %}" alt="" style="width:50px; height: auto;"/></span>
 
    {% endblock%}    

blog/templates/blog/jardin_visu.html
{% extends "base.html" %}
{% block title %}Le Jardin Buissonnier : Le Blog{% endblock %}
{% block content %}
 <div style="padding-left:150px; padding-right:150px;">    
{% for article in derniers_articles %}
    <div class="article">
    	<h3>{{ article.titre }}</h3>
    	<p>{{ article.contenu|truncatewords_html:80 }}</p>
        <p><a href="{% url "blog.views.lire" article.id %}">Lire la suite</a>
    </div>
{% empty %}
    <p>Aucun article.</p>
{% endfor %}
</div>
{% endblock %}

blog/templates/blog/lire.html
<h1>{{ article.titre }}</h1>
<p class="infos">article publié le {{ article.date|date:"DATE_FORMAT" }}</p>
<div class="contenu">{{ article.contenu|linebreaks }}</div>
<img src="{{ article.photo.url }}"/>

contact/templates/contact/contact_accueil.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Le Jardin Buissonnier : Contact{% endblock %}
{% block content %}
  <div style="padding-left:150px; padding-right:150px;">

 <div class="div_container">
 <p class="titre_article"> Qui sommes-nous ?</p>
</div>

 <div class="ligne_verte"> &nbsp; </div>

<div class="cases">
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
  <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
 <div class="case_contact"> </div>
</div>


 <div class="div_container">
 <p class="titre_article" >Où nous trouver ?</p>
</div>

 <div class="ligne_verte"> &nbsp; </div>
 
 <img src="{% static 'img/jardin_buissonnier.png' %}" style="width: 100%; height:auto;" /> 
 
 
 <ul style="font-family: 'LeagueGothic'; color: #556242; font-size:16pt;" >
    <li class="cl_1"> Directement au Jardin Buissonnier</li>
    Vente à la ferme -  Lieu dit le Buisson - 24470 Saint-Pardoux-la-Rivière :
        <ul>
            <li class="cl_2"> Tous les soirs : 17h-19h </li>
            <li class="cl_2"> Sur rendez-vous via le formulaire de contact </li>
        </ul>
    <li class="cl_1"> Aux marchés </li>
    Marché de Saint-Pardoux-la-Rivière
        <ul>
            <li class="cl_2"> Jeudi : 9h-12h </li>
        </ul>
    <li class="cl_1"> En magasin de producteurs</li>
        <ul>
            <li class="cl_2"> Saveur Nature - Boutique de producteurs et Epicerie Bio <br /> Le Bourg, 24450 Saint-Pierre-de-Frugie </li>
        </ul>
    <li class="cl_1"> Nos partenaires </li>
        <ul> 
            <li class="cl_2"> Grand Hôtel Pélisson - 3 Place Alfred Agard, 24300 Nontron </li>
            <li class="cl_2"> Boulangerie - Le Relais de Compostelle  - 72 Rue Republique, 24450 La Coquille </li>
        </ul>
 </ul>
<img src="{% static 'img/carte.svg' %}" style="width: 100%; height:auto; margin-top:-10px;" /> 
<div class="div_container">
 <p class="titre_article">Nous contacter</p>
</div>

 <div class="ligne_verte"> &nbsp; </div>
 
 {% if envoi %}Votre message a bien été envoyé !{% endif %}
 <div class="formulaire">
 <form action="{% url "contact.views.contact" %}" method="post">

    {% csrf_token %}
    <p><label for="id_nom">Nom, Prénom :</label> <input id="id_nom" type="text" name="nom" maxlength="20" /></p>
    <p><label for="id_mail">Adresse mail :</label> <input type="text" name="mail" id="id_mail" /></p>
    <p><label for="id_numero">Numéro de téléphone :</label> <input id="id_numero" type="text" name="numero" maxlength="20" /></p>
    <p><label for="id_message">Message :</label> <textarea id="id_message" rows="10" cols="60" name="message"></textarea></p>
    
    
    <input type="submit" value="Envoyer &#9656;" class="bouton_vert" style="right:100px;"/>

</form>
</div>
 </div>
{% endblock %}

jardins/templates/jardins/jardin_accueil.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Le Jardin Buissonnier : Le Blog{% endblock %}
{% block content %}
<p> L'organisation des culltures en six jardins différents </p>
    <p> Et elle change tous les ans pour laisser respirer la terre </p>
 <div style="padding-left:170px; padding-right:150px;display:flex;flex-wrap: wrap;">    

    
    
    <div class="categorie_jardin"> 
        <img src="{% static 'img/cruciferes.png' %}" alt="cruciferes" style="width:218px; height: auto;"/>
    </div>
    <div class="categorie_jardin"> 
        <img src="{% static 'img/primeurs.png' %}" alt="primeurs" style="width:218px; height: auto;"/>
    </div>
    <div class="categorie_jardin"> 
        <img src="{% static 'img/liliaces.png' %}" alt="liliaces" style="width:218px; height: auto;"/>
    </div>
    <div class="categorie_jardin"> 
        <img src="{% static 'img/cruciferes.png' %}" alt="cruciferes" style="width:218px; height: auto;"/>
    </div>
    <div class="categorie_jardin"> 
        <img src="{% static 'img/cruciferes.png' %}" alt="cruciferes" style="width:218px; height: auto;"/>
    </div>
    <div class="categorie_jardin"> 
        <img src="{% static 'img/engrais.png' %}" alt="engrais" style="width:218px; height: auto;"/>
    </div>
    <p> Il n'y a rien qui pousse pour être mangé dans celui-là </p>
    <p> Ce sont uniquement des plantes qui permettent d'enrichir le sol pour la prochaine rotation </p>

</div>
{% endblock %}

jardins/templates/jardins/jardin_visu.html
{% extends "base.html" %}
{% block title %}Le Jardin Buissonnier : Le Blog{% endblock %}
{% block content %}
 <div style="padding-left:150px; padding-right:150px;">    
{% for article in derniers_articles %}
    <div class="article">
    	<h3>{{ article.titre }}</h3>
    	<p>{{ article.contenu|truncatewords_html:80 }}</p>
        <p><a href="{% url "blog.views.lire" article.id %}">Lire la suite</a>
    </div>
{% empty %}
    <p>Aucun article.</p>
{% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />      
    {% load staticfiles %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}Le Jardin Buissonnier{% endblock %}</title>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</head>

<body>
      
<header>
    <div id="entete">
        <img src="{% static 'img/entete.svg' %}" alt="Le jardin buissonnier" id="entete_image"/>
    </div>
</header>

<div id="conteneur">
<div id="menu">
<nav class="menu_nav">
{% block nav %}
<a href="{% url "accueil.views.page_accueil" %}"><div class="element_menu"> <img src="{% static 'img/accueil.svg' %}" alt="icone accueil" class="icone_menu" />  Accueil</div></a>
<a href="{% url "jardins.views.jardin_accueil" %}" ><div class="element_menu"> <img src="{% static 'img/auxjardins.svg' %}" alt="icone accueil" class="icone_menu"/> Aux Jardins</div></a>
<a href="{% url "blog.views.accueil" %}"><div class="element_menu"> <img src="{% static 'img/blog.svg' %}" alt="icone accueil" class="icone_menu" /> Blog</div></a>
<a href="{% url "contact.views.contact" %}" ><div class="element_menu"> <img src="{% static 'img/contact.svg' %}" alt="icone accueil" class="icone_menu" /> Contact</div></a>
<a href="#" ><div class="element_menu"> <img src="{% static 'img/monpanier.svg' %}" alt="icone accueil" class="icone_menu" /> Mon Panier</div></a>
{% endblock %}
</nav>
</div>
    
    <!-- Structure de la page -->
    
    <div id="Global">
        {% block content %}{% endblock%}    
    </div>

    {% block aside %}
    <script type="text/javascript">   
    console.log('Tut');
    console.log('page', pageYOffset);
    window.onscroll = function (e) {
      
      var body = document.body,
        html = document.documentElement;

      var height = Math.max( body.scrollHeight, body.offsetHeight,html.clientHeight, html.scrollHeight, html.offsetHeight );
      
      var your_div = document.getElementById('box_menu_lat');
      
      console.log('H', height);
      $('#box_menu_lat').css({
          'top':  Math.min(Math.max(210 + pageYOffset - 180, 210), height-770)
      });
      }
    </script>

    <div id="box_menu_lat">
    <div class="menu_lateral">
    <nav class="menu_lat_nav">
    {% block menu_lat %}
    <a href="#"> <div class="e_menu_lat"> <img src="{% static 'img/fleur.svg' %}" class="i_menu_lat"/> Menu</div></a>
    <a href="#"> <div class="e_menu_lat"> <img src="{% static 'img/fleur.svg' %}" class="i_menu_lat"/> Article suivant</div></a>
    <a href="#"> <div class="e_menu_lat"> <img src="{% static 'img/fleur.svg' %}" class="i_menu_lat"/> Article précédent</div></a>
    <a href="#"> <div class="e_menu_lat"> <img src="{% static 'img/fleur.svg' %}" class="i_menu_lat"/> Nous contacter</div></a>
    <a href="#"> <div class="e_menu_lat" style="color: #dde9af;;"> <img src="{% static 'img/fleur_verte.svg' %}" class="i_menu_lat"/> Retour à l'accueil</div></a>
    {% endblock %}
    </nav>
    </div>
    <span class="triangle_lat"> <img src="{% static 'img/triangle.svg' %}" alt="" style="width:50px; height: auto;"/></span>
    </div>

     
    {% endblock%}    
     <div style="clear: both;"></div>  
    <footer>
        <!-- Pied de page -->
        <span id="pied"> Le Jardin Buissonnier - Lieu dit Le Buisson - Saint-Pardoux-la-rivière - 24470 </span>
    </footer>
    <div id="bambou"> <img src="{% static 'img/bambou.svg' %}" alt="" /> </div>
</div>
</body>
</html>